### ISSUE TITLE
Viruus For Crash Windows

### ISSUE THREAD

**Issue by mahanzd1** [oldlaptop/dbluejay#1]
Crash Widows

**Comment by oldlaptop** [comment]
I'm sorry, I don't understand what this is about. dbluejay shouldn't be capable of "crashing Windows", or even triggering false positives from virus-scanning software. Can you explain what's wrong more precisely?

**Comment by mahanzd1** [comment]
Hello Durd, this is a virus that you have to insert into the USB and when the USB is connected to the computer it crashes. The only way to remove this USB is to connect it 5 times and it will be fixed.

**Comment by oldlaptop** [comment]
I still don't understand what you're talking about. dbluejay is (a) not a "virus", (b) doesn't have anything to do with USB or USB disks, and (c) certainly hasn't crashed any of my computers. I'm closing this for now as not topical; if you are in fact experiencing some kind of bug in dbluejay, please explain it, ideally including whatever error message you see.
